### ISSUE TITLE
You cant save configs

### ISSUE THREAD

**Issue by Wannab3** [spikeone83/NecroBot#1]
Hey, you cant save configs in the newest version. It just says check values every time, even if you didnt change anything.

Ur GUI is the greatest fork btw, keep it up! :+1:

**Comment by spikeone83** [comment]
I appreciate it!
I am merging with newer Necrobot build and they changed a lot of settings which I didn't finish implenting is why it's not saving, should be done soon :)

**Comment by spikeone83** [comment]
fixed :)
